In [ ]:
a= input("enter the name ")
b= int(input("enter the age "))
c= 50-b
print(a," has ",c," years for retiring")

enter the name ravi
enter the age 50
ravi  has  0  years for retiring


In [ ]:
a= input("enter the name ")
b= int(input("enter phone number "))
c= input("enter email id")
d= input("enter address")
print(a,"from",d,"thanks for shopping with Dmart")

enter the name bscanc
enter phone number 89937389
enter email idufcjbccslm
enter addressfchdhv
bscanc from fchdhv thanks for shopping with Dmart


In [ ]:
a= input("enter user name ")
b= int(input("enter age "))
c= input("enter address ")
print(a,"\n",b,"\n",c)
print(a)
print(b)
print(c)



enter user name ravi
enter age 35
enter address munbai
ravi 
 35 
 munbai
ravi
35
munbai


In [ ]:
a= int(input("enter a number "))
b= int(input("enter another number "))
print("values before swapping",a,b)
temp=a
a=b
b=temp
print("values after swapping",a,b)

KeyboardInterrupt: Interrupted by user

In [ ]:
a=5
b=6
a,b=b,a
print(a)
print(b)

6
5


In [ ]:
a=5
b=6
a=a+b
b=a-b
a=a-b
print(a)
print(b)

6
5


In [ ]:
a=5
b=6
a=a^b
b=a^b
a=a^b
print(a)
print(b)

6
5


In [ ]:
x=int(input("enter nidhi marks in maths"))
y=int(input("enter nidhi marks in science"))
z=int(input("enter nidhi marks in english"))
nidhi_total= x+y+z
a=int(input("enter shubh marks in maths"))
b=int(input("enter shubh marks in science"))
c=int(input("enter shubh marks in english"))
shubh_total=a+b+c
if nidhi_total==shubh_total:
  print("total are equal")
else:
  print("total are not equal")

enter nidhi marks in maths98
enter nidhi marks in science99
enter nidhi marks in english100
enter shubh marks in maths98
enter shubh marks in science98
enter shubh marks in english100
total are not equal


In [ ]:
time_sec=int(input("time taken by varun in seconds"))
time_min= time_sec//60
time_remainder=time_sec%60
print(time_min,"minutes and",time_remainder,"seconds")


time taken by varun in seconds90
1 minutes and 30 seconds


In [ ]:
farht=int(input("enter value in farenheit"))
celsius= (farht-32)*5/9
print(celsius)

enter value in farenheit55
12.777777777777779


In [ ]:
x=int(input("enter a value"))
y=x%10
print(y)
if y%2==0:
    print("the given number is even")
else:
    print("the given number is odd")



enter a value13
3
the given number is odd


In [ ]:
a=int(input("enter no of chocolates shubham have "))
b=int(input("enter no of chocolates shubham's first freind have "))
c=int(input("enter no of chocolates shubham's second friend have "))
d= a+b+c
e=d%3
f=3-e
print(f,"chocolates need to distribute equally among them")


enter no of chocolates shubham have 10
enter no of chocolates shubham's first freind have 10
enter no of chocolates shubham's second friend have 5
2 chocolates need to distribute equally among them


In [ ]:
x= int(input("enter a number"))
if(x%2==0):
    print("even number")
elif(x==0):
    print("numbar is zero")
elif(x>0):
    print("positive number")
elif(x<0):
    print("negative number")
else:
    print("odd number")

enter a number3
positive number


In [ ]:
num=int(input("enter a number"))
if (num>0):
    print("positive number")
    if (num%2==0):
        print("even number")
    else:
        print("odd number")
else:
    print("negative number")

enter a number8
positive number
even number


In [ ]:
ph= int(input("enter ph value"))
if(ph>=1 and ph<=3):
    print("strong acid")
elif(ph>=4 and ph<=6):
    print("weak acid")
elif(ph==7):
    print("neutral")
elif(ph>=8 and ph<=11):
    print("weak base")
elif(ph>=12 and ph<=14):
    print("strong base")
else:
    print("not valid ph level")



enter ph value2
strong acid


In [ ]:
x=float(input("enter the weight"))
y=float(input("enter the height"))
z=int(input("enter the age"))
bmi=(x/y**2)
if (z>=18 and z<=65):
    if(bmi<=18.4):
        print("underweight")
    elif(bmi>=18.5 and bmi<=24.9):
        print("healthy")
    else:
        print("overweight")
else:
  print("this age not applicable")

enter the weight80
enter the height2
enter the age17
this age not applicable


In [ ]:
#Ayear consists of 365 days.But once in 4years,it consists of 366 days and that is known as leap year.
#shisha wants to know whether the current year is leap or not.
#she found that any year divisible by 4 is leap year,if the yaer dicisible by 100 then it it will not be leap year.
#and if the numer is divisible by 400 is leap year. write python code to check given year is leap or not.
x=int(input("enter a year"))
if(x%4==0):     # this condition is enough to check leap year or not. here conditins given so extended the program.
    print("leap year")
elif(x%100==0):
    print("not leap year")
elif(x%400==0):
    print("leap year")
else:
    print("not leap year")

enter a year2026
not leap year


In [ ]:
#a farmer dug a flower bed of radius 7 m at the centre of a field,he needs to purchase fertilizer.
#If 1 kg of fertilizer required for 1 square meter area, how muchfertilizer should he purchase?
import math
radius=7
area= 3.142*radius**2
fertilizer=area
print("area of flower bed:",area,"square meters")
print("fertilizer required:",fertilizer,"kg")


area of flower bed: 153.958 square meters
fertilizer required: 153.958 kg


In [ ]:
#anu wants to fence the garden infront of her house, on three sides with length 20m,12m and 12m.
#find the cost of fencing at the rate of 150 per meter.
# Hint: find the perimeter and then calculate the cost of fencing.
side1=20
side2=12
side3=12
rate=150
perimeter= side1+side2+side3
total_cost= perimeter * rate
print("total length of fencing:",perimeter,"meters")
print("total cost of fencing:",total_cost,"rupees")


total length of fencing: 44 meters
total cost of fencing: 6600 rupees


In [ ]:
# write a python program to get a word as input and access and display each letter of word in a new line.
word= input("enter a word: ")
for i in word:
  print(i)

enter a word: welcome
w
e
l
c
o
m
e


In [ ]:
# write a program to create mirror image of given string. for ex: "wel"="lew"
# it is reverse of string also.
word=input("enter a word: ")
print(word[::-1])
    #or
#word=input("enter a word:")
# mirror= word[::-1]
# print(mirror)

enter a word: welcome
emoclew


In [ ]:
# write a code to create tables
for i in range(1,11):
    for j in range(1,11):
        print(i*j,end="\t")
    print()

1	2	3	4	5	6	7	8	9	10	
2	4	6	8	10	12	14	16	18	20	
3	6	9	12	15	18	21	24	27	30	
4	8	12	16	20	24	28	32	36	40	
5	10	15	20	25	30	35	40	45	50	
6	12	18	24	30	36	42	48	54	60	
7	14	21	28	35	42	49	56	63	70	
8	16	24	32	40	48	56	64	72	80	
9	18	27	36	45	54	63	72	81	90	
10	20	30	40	50	60	70	80	90	100	


In [ ]:
for i in range(1,6):
    for j in range(1,6):
        print("*",end=" ")
    print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
for i in range(1,6):
    for j in range(1,i+1):
        print("*",end=" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
for i in range(3):
    for j in range(5):
        if(i==0 or i==2 or j==0 or j==4):
            print("*",end=" ")
        else:
            print(" ",end=" ")
    print()

* * * * * 
*       * 
* * * * * 


In [ ]:
for i in range(5):
    for j in range(5-i):
        print("*",end=" ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
for i in range (5):
    for j in range(5-i-1):
        print(" ",end="")
    for k in range(i+1):
        print("*",end=" ")
    print()

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [ ]:
for i in range (5):
    for j in range(i):
        print(" ",end="")
    for k in range(5-i):
        print("*",end=" ")
    print()

* * * * * 
 * * * * 
  * * * 
   * * 
    * 


In [ ]:
for i in range (5):
    for j in range(5-i-1):
        print(" ",end="")
    for k in range(i+1):
        print("*",end=" ")
    print()
for i in range (5):
    for j in range(i):
        print(" ",end="")
    for k in range(5-i):
        print("*",end=" ")
    print()

    * 
   * * 
  * * * 
 * * * * 
* * * * * 
* * * * * 
 * * * * 
  * * * 
   * * 
    * 


In [ ]:
veggies=['carrot','brocolli','potato','asparagus']
veggies.insert(veggies.index("brocolli"),'celery')
print(veggies)

['carrot', 'celery', 'brocolli', 'potato', 'asparagus']


In [ ]:
#write a python code that creates a list of numbers from 1 to 40 that are divisible by 4 and print the list.
lst=[]

for i in range(1,41):
    if i%4==0:
        lst.append(i)
print(lst)




[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]


In [ ]:
#important: write a python code to take input for two lists from user and print the elements which are common in both the lists.

lst1=list(map(int,input("enter elements of first list").split()))
lst2=list(map(int,input("enter elements of second list").split()))

common=[]
for i in lst1:
  if i in lst2:
    common.append(i)
print("common elements:",common)

enter elements of first list1 2 3 4 5
enter elements of second list3 4 5 6 7
common elements: [3, 4, 5]


In [ ]:
##nested dictionary

myfamily={
    "child1":{
        "name":"vikas",
        "year":2000
    },
    "child2":{
        "name":"vilas",
        "year":2001
    },
    "child3":{
        "name":"vishwas",
        "year":2002
    }
}
print(myfamily)

{'child1': {'name': 'vikas', 'year': 2000}, 'child2': {'name': 'vilas', 'year': 2001}, 'child3': {'name': 'vishwas', 'year': 2002}}


In [ ]:
##nested dictionary another way

child1={
    "name":"vikas",
    "year":2000
}
child2={
    "name":"vilas",
    "year":2001
}
child3={
    "name":"vishwas",
    "year":2002
}

myfamily={
    "child1":child1,
    "child2":child2,
    "child3":child3
}
print(myfamily)

{'child1': {'name': 'vikas', 'year': 2000}, 'child2': {'name': 'vilas', 'year': 2001}, 'child3': {'name': 'vishwas', 'year': 2002}}


In [ ]:
def add(name,*marks):
  sum=0
  for i in marks:
    sum=sum+i
  return sum
add("ajay", 76,34,56)

166

In [ ]:
def factorial(n):
  if (n==0) or (n==1):
    return 1
  else:
    return (n*factorial(n-1))
num=5
print("the number is:", num)
print("the factorial is:", factorial(num))

the number is: 5
the factorial is: 120


In [ ]:
class sample:
  x,y=10,20
s=sample()
print("value of x is:",s.x)
print("value of y is:",s.y)
print("sum of x and y is:", s.x + s.y)

value of x is: 10
value of y is: 20
sum of x and y is: 30


In [ ]:
class student:
  mark1,mark2,mark3=45,67,89
  def process(self):
    sum=student.mark1+student.mark2+student.mark3
    avg=sum/3
    print(sum)
    print(avg)
s=student()
s.process()

201
67.0


##pandas

In [ ]:
import pandas as pd
l=[1,2,3,4,5]
df=pd.Series(l,index=['a','b','c','d','e'])
print(df)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
import pandas as pd
data={
    "calories":[100,200,300,400],
    "duration":[10,20,30,40]
    }
df1=pd.DataFrame(data,index=[1,2,3,4])

print(df1)

   calories  duration
1       100        10
2       200        20
3       300        30
4       400        40


In [ ]:
data=pd.DataFrame({
    "calories":[100,200,300,400],
    "duration":[10,20,30,40]
    })
print(data)

   calories  duration
0       100        10
1       200        20
2       300        30
3       400        40


In [ ]:
import pandas as pd
df= pd.DataFrame({"car":["bmw","volvo"],"passings":[5,6]})
print(df)
print("\n")
df1= pd.DataFrame({"car":["honda","hyundai"],"passings":[3,4]})
print(df1)
print("\n")
df2= df._append(df1,ignore_index=True)  ## in append function we can add only two tables
print(df2)
print("\n")
df3=pd.concat([df,df1,df2],ignore_index=True)  ## in concat function we can add multiple tables
print(df3)

     car  passings
0    bmw         5
1  volvo         6


       car  passings
0    honda         3
1  hyundai         4


       car  passings
0      bmw         5
1    volvo         6
2    honda         3
3  hyundai         4


       car  passings
0      bmw         5
1    volvo         6
2    honda         3
3  hyundai         4
4      bmw         5
5    volvo         6
6    honda         3
7  hyundai         4


In [ ]:
import pandas as pd
df= pd.DataFrame({"car":["bmw","volvo"],"passings":[5,6]})
print(df)
print("\n")
df.insert(2,"nation",["india","malaysia"])
print(df)


     car  passings
0    bmw         5
1  volvo         6


     car  passings    nation
0    bmw         5     india
1  volvo         6  malaysia


In [ ]:
import pandas as pd
df= pd.DataFrame({"car":["bmw","volvo"],"passings":[5,6]})
df1= pd.DataFrame({"car":["honda","hyundai"],"passings":[3,4]})
df2= df._append(df1,ignore_index=True)  ## in append function we can add only two tables
df3=pd.concat([df,df1,df2],ignore_index=True)  ## in concat function we can add multiple tables
df3.insert(2,"nation","any")
print(df3)

       car  passings nation
0      bmw         5    any
1    volvo         6    any
2    honda         3    any
3  hyundai         4    any
4      bmw         5    any
5    volvo         6    any
6    honda         3    any
7  hyundai         4    any


In [ ]:
import pandas as pd
df=pd.DataFrame({"temp_c":[40,37]},index=["malaysia","maldives"])
df.assign(temp_f=df["temp_c"]*9/5+32)

,temp_c,temp_f
malaysia,40,104.0
maldives,37,98.6


In [ ]:
import numpy as np
arr=np.array(43) ##0D array
print(arr)

43


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5]) ##1D array
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]]) ## 2D array
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) ## 3D array
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
